<a href="https://colab.research.google.com/github/humairaneha/Learning-Pytorch/blob/main/PyTorch_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [391]:
import torch
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [392]:
def set_all_seeds(seed):
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# Set a fixed seed for reproducibility
SEED = 42
set_all_seeds(SEED)

In [393]:
df = pd.read_csv('https://raw.githubusercontent.com/prashant-kikani/breast-cancer-detection/refs/heads/master/breast-cancer-data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [394]:
df.shape

(569, 33)

In [395]:
#drop unencessary columns

df.drop(columns=['id','Unnamed: 32'],inplace=True) # modify the dataframe directly

df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

# train test split

In [396]:
X_train, X_test, y_train , y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2)

In [397]:
# Update train_test_split to use a fixed random_state
X_train, X_test, y_train , y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0], test_size=0.2, random_state=SEED)

#scaling

When using StandardScaler (or any other fit-based transformer), fit_transform is applied to X_train to calculate the mean and standard deviation from the training data and then scale it. This is crucial because it prevents 'data leakage' from the test set into the training process. The transform method is then applied to X_test using the same mean and standard deviation learned from X_train. This ensures that the test data is scaled consistently with the training data, without the test data influencing the scaling parameters, which could lead to an overly optimistic evaluation of the model's performance.

In [398]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train[:5,:]

array([[-1.44075296, -0.43531947, -1.36208497, -1.1391179 ,  0.78057331,
         0.71892128,  2.82313451, -0.11914956,  1.09266219,  2.45817261,
        -0.26380039, -0.01605246, -0.47041357, -0.47476088,  0.83836493,
         3.25102691,  8.43893667,  3.39198733,  2.62116574,  2.06120787,
        -1.23286131, -0.47630949, -1.24792009, -0.97396758,  0.72289445,
         1.18673232,  4.67282796,  0.9320124 ,  2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167,  1.85197292,  1.319843  ,
         3.42627493,  2.01311199,  2.66503199,  2.1270036 ,  1.55839569,
         0.80531919, -0.81268678,  0.75195659,  0.87716951, -0.89605315,
         1.18122247,  0.18362761,  0.60059598, -0.31771686,  0.52963649,
         2.17331385,  1.3112795 ,  2.08161691,  2.1374055 ,  0.76192793,
         3.26560084,  1.92862053,  2.6989469 ,  1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, -1.10978518, -1.33264483,
        -0.30735463, -0.36555756, -0.69650228,  1.93033305,  0.95437877,
         0.02752055,  1.96305996, -0.12095781, -0.35077918,  0.57276579,
         0.7394992 ,  0.32065553,  0.58946222,  2.61504052,  0.71892779,
        -1.29528358, -1.04081128, -1.24522047, -0.99971493, -1.43869328,
        -0.54856427, -0.64491059, -0.97023893,  0.59760192,  0.0578942 ],
       [-0.98179678,  1.41622208, -0.98258746, -0.86694414,  0.05938999,
        -0.59678772, -0.82020317, -0.84511471,  0.31326409,  0.07404147,
        -0.53850473,  0.53647286, -0.65795   , -0.49659014,  0.0654747 ,
        -0.82240418, -0.68556537, -0.89848456,  0.12329928, -0.43154667,
        -0.8291973 ,  1.59353039, -0.87357215, -0.74294685,  0.79662437,
        -0.7293916 , -0.77494969, -0.80948314,  0.79892783, -0.1344968 ],
       [-1.11769991, -1.0102595 , -1.12500192, -0.96594206,  1.26951116,
        -0.43900185, -0.98334145, -0.93059974,  3.39443604,  0.95021314,
         0.40227808,  0.4403815 ,  0.21931447, -0.11553185,  0.17191085,
        -0.78797021, -0.78350919, -0.58864808,  2.60401511,  0.76598123,
        -1.08512861, -1.3346163 , -1.11713828, -0.89654919, -0.17487574,
        -0.99507862, -1.20914641, -1.35458167,  1.03354385, -0.20573196]])

In [399]:
y_train # categorical values

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

#Label Encoding

In [400]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

# Numpy arrays to Pytorch tensors

In [401]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [402]:
X_train_tensor.shape

torch.Size([455, 30])

In [403]:
y_train_tensor_processed= y_train_tensor.double().unsqueeze(1)

#Defining the model

In [404]:
# only one neuron
class MySimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True) # 1 bias for 1 neuron

  def forward(self,X):
      self.output =  torch.matmul(X, self.weights) + self.bias
      return self.output

  def loss_function(self,y_pred,y_true):

      # clamp predictions to avoid log(0)

      epsilon = 1e-7
      y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)
      #calculate loss : average
      loss=-(y_true * torch.log(y_pred) + (1 - y_true) * torch.log(1 - y_pred)).mean()
      return loss

class Activation_sigmoid():

  def forward(self, Z):
    self.output = torch.sigmoid(Z)
    return self.output

#Important Parameters

In [408]:
learning_rate = 0.1
epochs = 25

# Training Pipeline

In [406]:
model = MySimpleNN(X_train_tensor)
model.weights
model.bias

# define loop ( epoch )
for  epoch in range(epochs):


# forward pass

  layer_output = model.forward(X_train_tensor)

  sigmoid = Activation_sigmoid()
  y_pred = sigmoid.forward(layer_output)





# loss calculate
  loss = model.loss_function(y_pred,y_train_tensor)
  print(loss)







# backward pass

  loss.backward()

# # weight and bias update
  with torch.no_grad():
    model.weights -=  learning_rate * model.weights.grad
    model.bias-= learning_rate * model.bias.grad
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

tensor(2.9616, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 1, Loss: 2.9615699828457833
tensor(2.8131, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 2, Loss: 2.8131138964342184
tensor(2.6646, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 3, Loss: 2.6646426866228032
tensor(2.5100, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 4, Loss: 2.5100000196924688
tensor(2.3506, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 5, Loss: 2.350565750514645
tensor(2.1948, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 6, Loss: 2.1948220587223157
tensor(2.0412, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 7, Loss: 2.041202943133097
tensor(1.8887, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 8, Loss: 1.8887141852208467
tensor(1.7411, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 9, Loss: 1.74105313797397
tensor(1.5995, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 10, Loss: 1.5995104593170377
tensor(1.4694, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 11, Loss: 1.4694172242025978
tensor(1.3495, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 12, Loss: 1.3495022527245604
tensor(1.2372, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 13, Loss: 1.2372197313390139
tensor(1.1393, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 14, Loss: 1.1393332310137823
tensor(1.0578, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 15, Loss: 1.057799606987682
tensor(0.9917, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 16, Loss: 0.9917333787414774
tensor(0.9393, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 17, Loss: 0.9393425388036476
tensor(0.8983, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 18, Loss: 0.8982718868958073
tensor(0.8661, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 19, Loss: 0.866083022079926
tensor(0.8406, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 20, Loss: 0.8406139677094522
tensor(0.8201, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 21, Loss: 0.8201319124168504
tensor(0.8033, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 22, Loss: 0.8033363650325822
tensor(0.7893, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 23, Loss: 0.7892919273911199
tensor(0.7773, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 24, Loss: 0.7773422595804
tensor(0.7670, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 25, Loss: 0.7670303915970541
tensor(0.7580, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 26, Loss: 0.7580349913956401
tensor(0.7501, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 27, Loss: 0.7501242066018178
tensor(0.7431, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 28, Loss: 0.7431247792372371
tensor(0.7369, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 29, Loss: 0.7369025584959447
tensor(0.7314, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 30, Loss: 0.7313505198862026
tensor(0.7264, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 31, Loss: 0.726381282071107
tensor(0.7219, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 32, Loss: 0.7219222076329906
tensor(0.7179, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 33, Loss: 0.717912025858256
tensor(0.7143, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 34, Loss: 0.7142984179938772
tensor(0.7110, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 35, Loss: 0.7110362539025574
tensor(0.7081, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 36, Loss: 0.7080862856586723
tensor(0.7054, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 37, Loss: 0.7054141646392728
tensor(0.7030, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 38, Loss: 0.7029896874535287
tensor(0.7008, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 39, Loss: 0.7007862039565582
tensor(0.6988, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 40, Loss: 0.6987801410997153
tensor(0.6970, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 41, Loss: 0.6969506110550586
tensor(0.6953, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 42, Loss: 0.6952790822130323
tensor(0.6937, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 43, Loss: 0.6937490984858536
tensor(0.6923, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 44, Loss: 0.6923460368594894
tensor(0.6911, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 45, Loss: 0.6910568960884127
tensor(0.6899, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 46, Loss: 0.6898701113598821
tensor(0.6888, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 47, Loss: 0.6887753910317751
tensor(0.6878, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 48, Loss: 0.6877635724070086
tensor(0.6868, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 49, Loss: 0.6868264940996001
tensor(0.6860, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 50, Loss: 0.6859568829682453
tensor(0.6851, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 51, Loss: 0.6851482539031544
tensor(0.6844, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 52, Loss: 0.6843948209887788
tensor(0.6837, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 53, Loss: 0.6836914187529541
tensor(0.6830, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 54, Loss: 0.6830334323670437
tensor(0.6824, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 55, Loss: 0.6824167357916184
tensor(0.6818, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 56, Loss: 0.6818376369742247
tensor(0.6813, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 57, Loss: 0.6812928293039311
tensor(0.6808, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 58, Loss: 0.6807793486142637
tensor(0.6803, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 59, Loss: 0.6802945351036449
tensor(0.6798, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 60, Loss: 0.679835999611821
tensor(0.6794, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 61, Loss: 0.6794015937529599
tensor(0.6790, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 62, Loss: 0.6789893834618482
tensor(0.6786, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 63, Loss: 0.6785976255595536
tensor(0.6782, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 64, Loss: 0.6782247469895981
tensor(0.6779, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 65, Loss: 0.6778693264155582
tensor(0.6775, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 66, Loss: 0.6775300779065637
tensor(0.6772, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 67, Loss: 0.6772058364687901
tensor(0.6769, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 68, Loss: 0.6768955452091235
tensor(0.6766, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 69, Loss: 0.6765982439420959
tensor(0.6763, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 70, Loss: 0.6763130590732345
tensor(0.6760, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 71, Loss: 0.6760391946115014
tensor(0.6758, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 72, Loss: 0.6757759241807274
tensor(0.6755, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 73, Loss: 0.675522583915191
tensor(0.6753, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 74, Loss: 0.6752785661379253
tensor(0.6750, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 75, Loss: 0.6750433137321991
tensor(0.6748, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 76, Loss: 0.6748163151270796
tensor(0.6746, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 77, Loss: 0.6745970998272045
tensor(0.6744, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 78, Loss: 0.6743852344250278
tensor(0.6742, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 79, Loss: 0.6741803190409754
tensor(0.6740, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 80, Loss: 0.6739819841432728
tensor(0.6738, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 81, Loss: 0.6737898877047869
tensor(0.6736, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 82, Loss: 0.6736037126591501
tensor(0.6734, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 83, Loss: 0.673423164622773
tensor(0.6732, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 84, Loss: 0.6732479698531979
tensor(0.6731, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 85, Loss: 0.6730778734176205
tensor(0.6729, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 86, Loss: 0.6729126375484087
tensor(0.6728, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 87, Loss: 0.6727520401650825
tensor(0.6726, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 88, Loss: 0.6725958735445619
tensor(0.6724, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 89, Loss: 0.6724439431235449
tensor(0.6723, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 90, Loss: 0.6722960664187158
tensor(0.6722, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 91, Loss: 0.6721520720520868
tensor(0.6720, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 92, Loss: 0.6720117988702152
tensor(0.6719, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 93, Loss: 0.6718750951472929
tensor(0.6717, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 94, Loss: 0.6717418178632338
tensor(0.6716, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 95, Loss: 0.6716118320488675
tensor(0.6715, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 96, Loss: 0.6714850101912319
tensor(0.6714, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 97, Loss: 0.6713612316927283
tensor(0.6712, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 98, Loss: 0.6712403823785978
tensor(0.6711, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 99, Loss: 0.6711223540477799
tensor(0.6710, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 100, Loss: 0.6710070440627683
tensor(0.6709, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 101, Loss: 0.6708943549745404
tensor(0.6708, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 102, Loss: 0.6707841941790811
tensor(0.6707, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 103, Loss: 0.6706764736023849
tensor(0.6706, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 104, Loss: 0.6705711094111619
tensor(0.6705, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 105, Loss: 0.6704680217467722
tensor(0.6704, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 106, Loss: 0.6703671344801667
tensor(0.6703, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 107, Loss: 0.6702683749858627
tensor(0.6702, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 108, Loss: 0.6701716739331746
tensor(0.6701, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 109, Loss: 0.670076965093119
tensor(0.6700, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 110, Loss: 0.6699841851595653
tensor(0.6699, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 111, Loss: 0.669893273583363
tensor(0.6698, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 112, Loss: 0.6698041724182922
tensor(0.6697, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 113, Loss: 0.6697168261778136
tensor(0.6696, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 114, Loss: 0.6696311817016888
tensor(0.6695, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 115, Loss: 0.6695471880316355
tensor(0.6695, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 116, Loss: 0.6694647962952678
tensor(0.6694, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 117, Loss: 0.6693839595976409
tensor(0.6693, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 118, Loss: 0.6693046329197867
tensor(0.6692, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 119, Loss: 0.6692267730236859
tensor(0.6692, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 120, Loss: 0.6691503383631721
tensor(0.6691, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 121, Loss: 0.6690752890003147
tensor(0.6690, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 122, Loss: 0.6690015865268647
tensor(0.6689, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 123, Loss: 0.6689291939903853
tensor(0.6689, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 124, Loss: 0.6688580758247267
tensor(0.6688, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 125, Loss: 0.6687881977845336
tensor(0.6687, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 126, Loss: 0.6687195268834967
tensor(0.6687, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 127, Loss: 0.668652031336089
tensor(0.6686, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 128, Loss: 0.668585680502548
tensor(0.6685, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 129, Loss: 0.6685204448368861
tensor(0.6685, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 130, Loss: 0.6684562958377247
tensor(0.6684, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 131, Loss: 0.668393206001773
tensor(0.6683, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 132, Loss: 0.6683311487797727
tensor(0.6683, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 133, Loss: 0.668270098534763
tensor(0.6682, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 134, Loss: 0.668210030502511
tensor(0.6682, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 135, Loss: 0.6681509207539793
tensor(0.6681, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 136, Loss: 0.6680927461597066
tensor(0.6680, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 137, Loss: 0.6680354843559848
tensor(0.6680, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 138, Loss: 0.6679791137127277
tensor(0.6679, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 139, Loss: 0.6679236133029316
tensor(0.6679, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 140, Loss: 0.6678689628736371
tensor(0.6678, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 141, Loss: 0.6678151428183046
tensor(0.6678, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 142, Loss: 0.6677621341505257
tensor(0.6677, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 143, Loss: 0.6677099184789943
tensor(0.6677, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 144, Loss: 0.6676584779836705
tensor(0.6676, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 145, Loss: 0.6676077953930681
tensor(0.6676, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 146, Loss: 0.6675578539626092
tensor(0.6675, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 147, Loss: 0.6675086374539858
tensor(0.6675, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 148, Loss: 0.6674601301154772
tensor(0.6674, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 149, Loss: 0.6674123166631704
tensor(0.6674, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 150, Loss: 0.6673651822630383
tensor(0.6673, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 151, Loss: 0.6673187125138326
tensor(0.6673, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 152, Loss: 0.6672728934307449
tensor(0.6672, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 153, Loss: 0.6672277114298024
tensor(0.6672, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 154, Loss: 0.6671831533129571
tensor(0.6671, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 155, Loss: 0.6671392062538367
tensor(0.6671, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 156, Loss: 0.6670958577841207
tensor(0.6671, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 157, Loss: 0.6670530957805137
tensor(0.6670, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 158, Loss: 0.6670109084522866
tensor(0.6670, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 159, Loss: 0.6669692843293555
tensor(0.6669, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 160, Loss: 0.6669282122508738
tensor(0.6669, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 161, Loss: 0.6668876813543124
tensor(0.6668, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 162, Loss: 0.6668476810650051
tensor(0.6668, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 163, Loss: 0.6668082010861365
tensor(0.6668, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 164, Loss: 0.6667692313891497
tensor(0.6667, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 165, Loss: 0.6667307622045581
tensor(0.6667, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 166, Loss: 0.6666927840131368
tensor(0.6667, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 167, Loss: 0.6666552875374812
tensor(0.6666, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 168, Loss: 0.6666182637339115
tensor(0.6666, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 169, Loss: 0.6665817037847097
tensor(0.6665, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 170, Loss: 0.6665455990906719
tensor(0.6665, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 171, Loss: 0.6665099412639623
tensor(0.6665, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 172, Loss: 0.6664747221212562
tensor(0.6664, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 173, Loss: 0.6664399336771558
tensor(0.6664, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 174, Loss: 0.6664055681378694
tensor(0.6664, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 175, Loss: 0.6663716178951404
tensor(0.6663, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 176, Loss: 0.6663380755204157
tensor(0.6663, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 177, Loss: 0.6663049337592416
tensor(0.6663, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 178, Loss: 0.6662721855258791
tensor(0.6662, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 179, Loss: 0.6662398238981259
tensor(0.6662, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 180, Loss: 0.6662078421123397
tensor(0.6662, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 181, Loss: 0.6661762335586493
tensor(0.6661, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 182, Loss: 0.6661449917763497
tensor(0.6661, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 183, Loss: 0.6661141104494699
tensor(0.6661, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 184, Loss: 0.6660835834025088
tensor(0.6661, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 185, Loss: 0.6660534045963278
tensor(0.6660, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 186, Loss: 0.6660235681241984
tensor(0.6660, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 187, Loss: 0.6659940682079929
tensor(0.6660, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 188, Loss: 0.6659648991945165
tensor(0.6659, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 189, Loss: 0.6659360555519728
tensor(0.6659, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 190, Loss: 0.665907531866555
tensor(0.6659, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 191, Loss: 0.6658793228391634
tensor(0.6659, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 192, Loss: 0.6658514232822347
tensor(0.6658, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 193, Loss: 0.6658238281166898
tensor(0.6658, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 194, Loss: 0.6657965323689844
tensor(0.6658, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 195, Loss: 0.6657695311682641
tensor(0.6657, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 196, Loss: 0.6657428197436193
tensor(0.6657, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 197, Loss: 0.6657163934214345
tensor(0.6657, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 198, Loss: 0.6656902476228274
tensor(0.6657, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 199, Loss: 0.6656643778611754
tensor(0.6656, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 200, Loss: 0.6656387797397272
tensor(0.6656, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 201, Loss: 0.6656134489492921
tensor(0.6656, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 202, Loss: 0.6655883812660089
tensor(0.6656, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 203, Loss: 0.6655635725491863
tensor(0.6655, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 204, Loss: 0.6655390187392151
tensor(0.6655, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 205, Loss: 0.6655147158555489
tensor(0.6655, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 206, Loss: 0.6654906599947494
tensor(0.6655, dtype=torch.float64, grad_fn=<NegBackward0>)
Epoch: 207, Loss: 0.6654668473285952

# model evaluation

In [407]:
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = sigmoid.forward(y_pred)
  y_pred = (y_pred > 0.9).float()
  accuracy = ( y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')

Accuracy: 0.6228070259094238